### ISSUE TITLE
missing license information

### ISSUE THREAD

**Issue by Tyrael** [dhotson/fdopen-php#2]
you didn't specified the license for this project.
I would propose to use either PHP compatible BSD license, or the PHP license itself:
http://php.net/license/index.php
http://www.php.net/license/contrib-guidelines-code.php

**Comment by dhotson** [comment]
Yep, I'm not too fussy about licensing. I usually go for something permissive like MIT or BSD.

I think most PHP extensions usually use the PHP license, so I think I'll probably go with that.

**Comment by dhotson** [comment]
Added PHP license in c7bdeb420b40af600ea5375b15421e238bdbf479
